// Generated by gencpp from file platform_lift/MoveLiftResult.msg
// DO NOT EDIT!


#ifndef PLATFORM_LIFT_MESSAGE_MOVELIFTRESULT_H
#define PLATFORM_LIFT_MESSAGE_MOVELIFTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platform_lift
{
template <class ContainerAllocator>
struct MoveLiftResult_
{
  typedef MoveLiftResult_<ContainerAllocator> Type;

  MoveLiftResult_()
    : current_position(0)  {
    }
  MoveLiftResult_(const ContainerAllocator& _alloc)
    : current_position(0)  {
  (void)_alloc;
    }



   typedef uint16_t _current_position_type;
  _current_position_type current_position;





  typedef boost::shared_ptr< ::platform_lift::MoveLiftResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platform_lift::MoveLiftResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLiftResult_

typedef ::platform_lift::MoveLiftResult_<std::allocator<void> > MoveLiftResult;

typedef boost::shared_ptr< ::platform_lift::MoveLiftResult > MoveLiftResultPtr;
typedef boost::shared_ptr< ::platform_lift::MoveLiftResult const> MoveLiftResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platform_lift::MoveLiftResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platform_lift::MoveLiftResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::platform_lift::MoveLiftResult_<ContainerAllocator1> & lhs, const ::platform_lift::MoveLiftResult_<ContainerAllocator2> & rhs)
{
  return lhs.current_position == rhs.current_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::platform_lift::MoveLiftResult_<ContainerAllocator1> & lhs, const ::platform_lift::MoveLiftResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace platform_lift

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::MoveLiftResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::MoveLiftResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::MoveLiftResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "844d4bef22690a2e14f414e468a4c37a";
  }

  static const char* value(const ::platform_lift::MoveLiftResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x844d4bef22690a2eULL;
  static const uint64_t static_value2 = 0x14f414e468a4c37aULL;
};

template<class ContainerAllocator>
struct DataType< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platform_lift/MoveLiftResult";
  }

  static const char* value(const ::platform_lift::MoveLiftResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"uint16 current_position\n"
;
  }

  static const char* value(const ::platform_lift::MoveLiftResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLiftResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platform_lift::MoveLiftResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platform_lift::MoveLiftResult_<ContainerAllocator>& v)
  {
    s << indent << "current_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.current_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATFORM_LIFT_MESSAGE_MOVELIFTRESULT_H
