// Generated by gencpp from file platform_lift/MoveLiftFeedback.msg
// DO NOT EDIT!


#ifndef PLATFORM_LIFT_MESSAGE_MOVELIFTFEEDBACK_H
#define PLATFORM_LIFT_MESSAGE_MOVELIFTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platform_lift
{
template <class ContainerAllocator>
struct MoveLiftFeedback_
{
  typedef MoveLiftFeedback_<ContainerAllocator> Type;

  MoveLiftFeedback_()
    : succeed(false)  {
    }
  MoveLiftFeedback_(const ContainerAllocator& _alloc)
    : succeed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeed_type;
  _succeed_type succeed;





  typedef boost::shared_ptr< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLiftFeedback_

typedef ::platform_lift::MoveLiftFeedback_<std::allocator<void> > MoveLiftFeedback;

typedef boost::shared_ptr< ::platform_lift::MoveLiftFeedback > MoveLiftFeedbackPtr;
typedef boost::shared_ptr< ::platform_lift::MoveLiftFeedback const> MoveLiftFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platform_lift::MoveLiftFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::platform_lift::MoveLiftFeedback_<ContainerAllocator1> & lhs, const ::platform_lift::MoveLiftFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.succeed == rhs.succeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::platform_lift::MoveLiftFeedback_<ContainerAllocator1> & lhs, const ::platform_lift::MoveLiftFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace platform_lift

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::platform_lift::MoveLiftFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d9c3b918a0afafeULL;
  static const uint64_t static_value2 = 0x09791ef8d7853918ULL;
};

template<class ContainerAllocator>
struct DataType< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platform_lift/MoveLiftFeedback";
  }

  static const char* value(const ::platform_lift::MoveLiftFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"bool succeed\n"
;
  }

  static const char* value(const ::platform_lift::MoveLiftFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLiftFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platform_lift::MoveLiftFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platform_lift::MoveLiftFeedback_<ContainerAllocator>& v)
  {
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATFORM_LIFT_MESSAGE_MOVELIFTFEEDBACK_H
