// Generated by gencpp from file platform_lift/PositionLiftResponse.msg
// DO NOT EDIT!


#ifndef PLATFORM_LIFT_MESSAGE_POSITIONLIFTRESPONSE_H
#define PLATFORM_LIFT_MESSAGE_POSITIONLIFTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platform_lift
{
template <class ContainerAllocator>
struct PositionLiftResponse_
{
  typedef PositionLiftResponse_<ContainerAllocator> Type;

  PositionLiftResponse_()
    : position(0)  {
    }
  PositionLiftResponse_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef uint16_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::platform_lift::PositionLiftResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platform_lift::PositionLiftResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionLiftResponse_

typedef ::platform_lift::PositionLiftResponse_<std::allocator<void> > PositionLiftResponse;

typedef boost::shared_ptr< ::platform_lift::PositionLiftResponse > PositionLiftResponsePtr;
typedef boost::shared_ptr< ::platform_lift::PositionLiftResponse const> PositionLiftResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platform_lift::PositionLiftResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::platform_lift::PositionLiftResponse_<ContainerAllocator1> & lhs, const ::platform_lift::PositionLiftResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::platform_lift::PositionLiftResponse_<ContainerAllocator1> & lhs, const ::platform_lift::PositionLiftResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace platform_lift

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platform_lift::PositionLiftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platform_lift::PositionLiftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platform_lift::PositionLiftResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6fa9d1b49571c7fff8bae5e451e5e59";
  }

  static const char* value(const ::platform_lift::PositionLiftResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6fa9d1b49571c7fULL;
  static const uint64_t static_value2 = 0xff8bae5e451e5e59ULL;
};

template<class ContainerAllocator>
struct DataType< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platform_lift/PositionLiftResponse";
  }

  static const char* value(const ::platform_lift::PositionLiftResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 position  \n"
"\n"
;
  }

  static const char* value(const ::platform_lift::PositionLiftResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionLiftResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platform_lift::PositionLiftResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platform_lift::PositionLiftResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATFORM_LIFT_MESSAGE_POSITIONLIFTRESPONSE_H
