// Generated by gencpp from file platform_lift/PositionLift.msg
// DO NOT EDIT!


#ifndef PLATFORM_LIFT_MESSAGE_POSITIONLIFT_H
#define PLATFORM_LIFT_MESSAGE_POSITIONLIFT_H

#include <ros/service_traits.h>


#include <platform_lift/PositionLiftRequest.h>
#include <platform_lift/PositionLiftResponse.h>


namespace platform_lift
{

struct PositionLift
{

typedef PositionLiftRequest Request;
typedef PositionLiftResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionLift
} // namespace platform_lift


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::platform_lift::PositionLift > {
  static const char* value()
  {
    return "e6fa9d1b49571c7fff8bae5e451e5e59";
  }

  static const char* value(const ::platform_lift::PositionLift&) { return value(); }
};

template<>
struct DataType< ::platform_lift::PositionLift > {
  static const char* value()
  {
    return "platform_lift/PositionLift";
  }

  static const char* value(const ::platform_lift::PositionLift&) { return value(); }
};


// service_traits::MD5Sum< ::platform_lift::PositionLiftRequest> should match
// service_traits::MD5Sum< ::platform_lift::PositionLift >
template<>
struct MD5Sum< ::platform_lift::PositionLiftRequest>
{
  static const char* value()
  {
    return MD5Sum< ::platform_lift::PositionLift >::value();
  }
  static const char* value(const ::platform_lift::PositionLiftRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::platform_lift::PositionLiftRequest> should match
// service_traits::DataType< ::platform_lift::PositionLift >
template<>
struct DataType< ::platform_lift::PositionLiftRequest>
{
  static const char* value()
  {
    return DataType< ::platform_lift::PositionLift >::value();
  }
  static const char* value(const ::platform_lift::PositionLiftRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::platform_lift::PositionLiftResponse> should match
// service_traits::MD5Sum< ::platform_lift::PositionLift >
template<>
struct MD5Sum< ::platform_lift::PositionLiftResponse>
{
  static const char* value()
  {
    return MD5Sum< ::platform_lift::PositionLift >::value();
  }
  static const char* value(const ::platform_lift::PositionLiftResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::platform_lift::PositionLiftResponse> should match
// service_traits::DataType< ::platform_lift::PositionLift >
template<>
struct DataType< ::platform_lift::PositionLiftResponse>
{
  static const char* value()
  {
    return DataType< ::platform_lift::PositionLift >::value();
  }
  static const char* value(const ::platform_lift::PositionLiftResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLATFORM_LIFT_MESSAGE_POSITIONLIFT_H
