(cl:defpackage platform_lift-msg
  (:use )
  (:export
   "<MOVELIFTACTION>"
   "MOVELIFTACTION"
   "<MOVELIFTACTIONFEEDBACK>"
   "MOVELIFTACTIONFEEDBACK"
   "<MOVELIFTACTIONGOAL>"
   "MOVELIFTACTIONGOAL"
   "<MOVELIFTACTIONRESULT>"
   "MOVELIFTACTIONRESULT"
   "<MOVELIFTFEEDBACK>"
   "MOVELIFTFEEDBACK"
   "<MOVELIFTGOAL>"
   "MOVELIFTGOAL"
   "<MOVELIFTRESULT>"
   "MOVELIFTRESULT"
  ))

