; Auto-generated. Do not edit!


(cl:in-package platform_lift-msg)


;//! \htmlinclude MoveLiftFeedback.msg.html

(cl:defclass <MoveLiftFeedback> (roslisp-msg-protocol:ros-message)
  ((succeed
    :reader succeed
    :initarg :succeed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MoveLiftFeedback (<MoveLiftFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveLiftFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveLiftFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name platform_lift-msg:<MoveLiftFeedback> is deprecated: use platform_lift-msg:MoveLiftFeedback instead.")))

(cl:ensure-generic-function 'succeed-val :lambda-list '(m))
(cl:defmethod succeed-val ((m <MoveLiftFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader platform_lift-msg:succeed-val is deprecated.  Use platform_lift-msg:succeed instead.")
  (succeed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveLiftFeedback>) ostream)
  "Serializes a message object of type '<MoveLiftFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succeed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveLiftFeedback>) istream)
  "Deserializes a message object of type '<MoveLiftFeedback>"
    (cl:setf (cl:slot-value msg 'succeed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveLiftFeedback>)))
  "Returns string type for a message object of type '<MoveLiftFeedback>"
  "platform_lift/MoveLiftFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveLiftFeedback)))
  "Returns string type for a message object of type 'MoveLiftFeedback"
  "platform_lift/MoveLiftFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveLiftFeedback>)))
  "Returns md5sum for a message object of type '<MoveLiftFeedback>"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveLiftFeedback)))
  "Returns md5sum for a message object of type 'MoveLiftFeedback"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveLiftFeedback>)))
  "Returns full string definition for message of type '<MoveLiftFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveLiftFeedback)))
  "Returns full string definition for message of type 'MoveLiftFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveLiftFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveLiftFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveLiftFeedback
    (cl:cons ':succeed (succeed msg))
))
