; Auto-generated. Do not edit!


(cl:in-package platform_lift-msg)


;//! \htmlinclude MoveLiftResult.msg.html

(cl:defclass <MoveLiftResult> (roslisp-msg-protocol:ros-message)
  ((current_position
    :reader current_position
    :initarg :current_position
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MoveLiftResult (<MoveLiftResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveLiftResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveLiftResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name platform_lift-msg:<MoveLiftResult> is deprecated: use platform_lift-msg:MoveLiftResult instead.")))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <MoveLiftResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader platform_lift-msg:current_position-val is deprecated.  Use platform_lift-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveLiftResult>) ostream)
  "Serializes a message object of type '<MoveLiftResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'current_position)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'current_position)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveLiftResult>) istream)
  "Deserializes a message object of type '<MoveLiftResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'current_position)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'current_position)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveLiftResult>)))
  "Returns string type for a message object of type '<MoveLiftResult>"
  "platform_lift/MoveLiftResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveLiftResult)))
  "Returns string type for a message object of type 'MoveLiftResult"
  "platform_lift/MoveLiftResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveLiftResult>)))
  "Returns md5sum for a message object of type '<MoveLiftResult>"
  "844d4bef22690a2e14f414e468a4c37a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveLiftResult)))
  "Returns md5sum for a message object of type 'MoveLiftResult"
  "844d4bef22690a2e14f414e468a4c37a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveLiftResult>)))
  "Returns full string definition for message of type '<MoveLiftResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%uint16 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveLiftResult)))
  "Returns full string definition for message of type 'MoveLiftResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%uint16 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveLiftResult>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveLiftResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveLiftResult
    (cl:cons ':current_position (current_position msg))
))
