; Auto-generated. Do not edit!


(cl:in-package platform_lift-msg)


;//! \htmlinclude MoveLiftResult.msg.html

(cl:defclass <MoveLiftResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MoveLiftResult (<MoveLiftResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveLiftResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveLiftResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name platform_lift-msg:<MoveLiftResult> is deprecated: use platform_lift-msg:MoveLiftResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MoveLiftResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader platform_lift-msg:success-val is deprecated.  Use platform_lift-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveLiftResult>) ostream)
  "Serializes a message object of type '<MoveLiftResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveLiftResult>) istream)
  "Deserializes a message object of type '<MoveLiftResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveLiftResult>)))
  "Returns string type for a message object of type '<MoveLiftResult>"
  "platform_lift/MoveLiftResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveLiftResult)))
  "Returns string type for a message object of type 'MoveLiftResult"
  "platform_lift/MoveLiftResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveLiftResult>)))
  "Returns md5sum for a message object of type '<MoveLiftResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveLiftResult)))
  "Returns md5sum for a message object of type 'MoveLiftResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveLiftResult>)))
  "Returns full string definition for message of type '<MoveLiftResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveLiftResult)))
  "Returns full string definition for message of type 'MoveLiftResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveLiftResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveLiftResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveLiftResult
    (cl:cons ':success (success msg))
))
