
  frame_id: base_link
  odom_frame_id: odom

  subscribe_depth: false
  subscribe_rgbd: false
  subscribe_rgb: false
  subscribe_scan: true

  queue_size: 10
  wait_for_transform_duration: 1
  odom_tf_linear_variance: 0.01
  odom_tf_angular_variance: 0.05

  Grid:
    Sensor: 0
    FromDepth: false


  RGBD:
    NeighborLinkRefining: true
    ProximityBySpace: true
    AngularUpdate: 0.01
    LinearUpdate: 0.01
    OptimizeFromGraphEnd: false

  Reg:
    Force3DoF: true
    Strategy: 1

  Icp:
    VoxelSize: 0.05
    MaxCorrespondenceDistance: 0.1