global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 3
   publish_frequency: 0.0
   rolling_window: true
   resolution: 0.2
   transform_tolerance: 1.0
   map_type: costmap
   inflation_radius: 1

   width: 15.0
   height: 15.0



