local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 3
   publish_frequency: 1
   static_map: false
   rolling_window: true
   width: 3.2
   height: 3.2
   resolution: 0.09
   transform_tolerance: 0.1
   map_type: costmap