base_local_planner: teb_local_planner/TebLocalPlannerROS
  

TebLocalPlannerROS:
 
 odom_topic: odom
 odom_frame: /odom
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.002
 global_plan_overwrite_orientation: False
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
 allow_init_with_backwards_motion: True

 use_proportional_saturation: true
 force_reinit_new_goal_dist: 0.3
 force_reinit_new_goal_angular: 0.78
 # Robot
         
 max_vel_x: 0.5
 max_vel_y: 0.5
 max_vel_x_backwards: 0.5
 max_vel_theta: 0.3
 acc_lim_x: 0.15
 acc_lim_y: 0.15
 acc_lim_theta: 0.3
 min_turning_radius: 0.0

 footprint_model: 
   type: "polygon"
   vertices: [[-0.5, 0.36], [-0.45, 0.36], [-0.45, 0.31], [0.45, 0.31], [0.45, -0.31], [0.5, -0.31], [0.5, -0.36], [0.45, -0.36], [0.45, -0.31], [-0.45, -0.31], [-0.45, 0.31], [-0.5, 0.31]]
 # GoalTolerance
    
 xy_goal_tolerance: 0.01
 yaw_goal_tolerance: 0.002
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.18
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5


 # Optimization
    
 no_inner_iterations: 3
 no_outer_iterations: 1
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.15
 weight_max_vel_x: 300
 weight_max_vel_y: 300
 weight_max_vel_theta: 1
 weight_acc_lim_x: 450
 weight_acc_lim_y: 550
 weight_acc_lim_theta: 450
 weight_kinematics_nh: 400
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 0
 weight_optimaltime: 5
 weight_obstacle: 400
 weight_dynamic_obstacle: 400 
 weight_inflation: 0.14
 weight_shortest_path: 1
 alternative_time_cost: False 
 weight_adapt_factor: 4



 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: True
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

selection_cost_hysteresis: 1.8
selection_prefer_initial_plan: 0.95

max_number_classes: 2
